#!/usr/bin/env bash
set -euo pipefail
trap "echo 'error: Script failed: see failed command above'" ERR

cd "$( dirname "$0" )/.." # Ensure to be at the project root directory

source "script/helpers/_helpers.sh"

begin

# You should set up any specific things for your environment here before your
# tests are run.

# TODO: do something

topic 'Calling `script/test`...' && script/test

end
