#!/usr/bin/env bash
set -euo pipefail
trap "echo 'error: Script failed: see failed command above'" ERR

cd "$( dirname "$0" )/.." # Ensure to be at the project root directory

source "script/helpers/_helpers.sh"

begin

# TODO: do something

end
