#!/usr/bin/env bash
set -euo pipefail
trap "echo 'error: Script failed: see failed command above'" ERR

cd "$( dirname "$0" )/.." # Ensure to be at the project root directory

source "script/helpers/_helpers.sh"

begin

if [[ "${CI:-,,}" = "true" ]]; then
  topic 'Testing in continuous integration server...'
  topic 'Calling `script/setup`...' && script/setup
else
  topic 'Testing in development environment...'
  topic 'Calling `script/update`...' && script/update
fi

# TODO: do something

end
