#!/usr/bin/env bash
set -euo pipefail
trap "echo 'error: Script failed: see failed command above'" ERR

cd "$( dirname "$0" )/.." # Ensure to be at the project root directory

source "script/helpers/_helpers.sh"

begin

# This is a good opportunity to run database migrations or any other things
# required to get the state of the app into shape for the current version that
# is checked out.

# TODO: do something

topic 'Calling `script/bootstrap`...' && script/bootstrap

end
